vars:
  # importe les variables (model_name, img_size, epochs, ...) dans le template
  - configs/train.yaml

stages:
  prepare:
    cmd: python -m src.data.prepare_splits
    deps:
      - src/data/prepare_splits.py
      - configs/paths.yaml
      - data/train_labels.csv
    outs:
      - data/splits

  train:
    # on lit les hyperparams dans configs/train.yaml (et on les logue dans MLflow)
    cmd: python -m src.train
    deps:
      - src/train.py
      - src/models/models.py
      - src/data/dataset.py
      - configs/train.yaml
      - configs/paths.yaml
      - data/splits
    params:
      - configs/train.yaml:
          - batch_size
          - img_size
          - epochs
          - lr
          - weight_decay
          - model_name
          - pretrained
          - num_workers
    outs:
      - checkpoints

  evaluate:
    # ⚠️ Windows: pas de "EVAL_JSON=..." (syntax POSIX) → on passe un flag --out-json
    cmd: python -m src.evaluate --model ${model_name} --weights checkpoints/best_${model_name}.pt --img-size ${img_size} --out-json reports/metrics.json
    deps:
      - src/evaluate.py
      - checkpoints
      - configs/train.yaml
      - configs/paths.yaml
      - src/data/dataset.py
    metrics:
      - reports/metrics.json
